inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

  Exclude:
    - 'db/*'
    - 'db/migrate/*'
