default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= CREDENTIALS[:username] %>
  password: <%= CREDENTIALS[:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: ererere_production
  username: <%= CREDENTIALS[:production][:username] %>
  password: <%= CREDENTIALS[:production][:password] %>
